<a href="https://colab.research.google.com/github/rajshreeathawale/python_Ass/blob/main/DBDA_numpy_classwork(Sept_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array(43)
b=np.array([])
c=np.array([[1,2,3,4],[1,3,5,7]])
print(c.ndim)
print(c.shape)
print(c.size)
print(c.T)
print(c.dtype)

2
(2, 4)
8
[[1 1]
 [2 3]
 [3 5]
 [4 7]]
int64


In [ ]:
a1=np.arange(0,1.2,0.2)
a1

In [ ]:
b1=np.random.random((2,3))
print(b1)

In [ ]:
z1=np.zeros((2,3),dtype=int)
print(z1)

In [ ]:
z1=np.ones((2,3),dtype=int)
print(z1)

In [ ]:
a2=np.array([[1,2,3,4],[9,8,7,6]])
b2=np.arange(9)
b3=b2.reshape(3,3)
print(b3)
print(a2[0:,1:])
print(a2[::-1,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 3 4]
 [8 7 6]]
[[6 7 8 9]
 [4 3 2 1]]


In [ ]:
b2=np.arange(9)
print(b2)
b3=b2.reshape(3,3)
b3

In [ ]:
bt=np.transpose(b3)
print(bt)

In [ ]:
a2=np.array([[11,2,31,478],[90,8,17,6]])
bs1=np.sort(a2,axis=1)
print(bs1)

[[  2  11  31 478]
 [  6   8  17  90]]


In [ ]:
a2=np.array([[11,2,31,478],[90,8,17,6]])
f1=a2.flatten()
print(f1)
f2=a2.flatten(order='F')
print(f2)

In [ ]:
import numpy as np
a=np.arange(1,11)
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(np.prod(a))
print(np.sqrt(a))
print(np.mean(a))

[ 1  2  3  4  5  6  7  8  9 10]
1
10
55
3628800
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
5.5


In [ ]:
a=np.arange(1,11)
a=a.reshape(2,5)
print(a)
min1=np.amin(a, axis=0)
print(min1)
min2=np.amin(a,axis=1)
print(min2)
max1=np.amax(a,axis=0)
print(max1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[1 6]
[ 6  7  8  9 10]


In [ ]:
z1=np.zeros((2,3),int)
print(z1)
print(np.all(z1))
print(np.all(a))
print(np.any(z1))
a1=[0,0,1,0]
print(np.any(a1))

[[0 0 0]
 [0 0 0]]
False
True
False
True


In [ ]:
a2=np.array([17,13,19])
b2=np.array(3)
print(a2+b2)
print(np.add(a2,b2))
print(np.subtract(a2,b2))
print(np.multiply(a2,b2))
print(np.divide(a2,b2))

[20 16 22]
[20 16 22]
[14 10 16]
[51 39 57]
[5.66666667 4.33333333 6.33333333]


In [ ]:
c=np.array([[5,25],[3,9]])
d=np.array(([4,16],[6,36]))
e=np.concatenate((c,d),axis=0)
print(e)
print(e.ndim)
e1=np.concatenate((c,d),axis=1)
print(e1)

[[ 5 25]
 [ 3  9]
 [ 4 16]
 [ 6 36]]
2
[[ 5 25  4 16]
 [ 3  9  6 36]]


In [ ]:
c=np.array([[5,25],[3,9]])
d=np.array(([4,16],[6,36]))
e=np.stack((c,d),axis=0)
print(e)
print(e.ndim)

[[[ 5 25]
  [ 3  9]]

 [[ 4 16]
  [ 6 36]]]
3


In [ ]:
c=np.array([[5,25],[3,9]])
d=np.array(([4,16],[6,36]))
e=np.vstack((c,d))
print(e)
print(e.ndim)

[[ 5 25]
 [ 3  9]
 [ 4 16]
 [ 6 36]]
2


In [ ]:
c=np.array([[5,25],[3,9]])
d=np.array(([4,16],[6,36]))
e=np.hstack((c,d))
print(e)
print(e.ndim)

[[ 5 25  4 16]
 [ 3  9  6 36]]
2


In [ ]:
x=np.array([[5,25],[3,9]])
x1=x.copy()
x1[0]=111
print(x1)
print(x)

[[111 111]
 [  3   9]]
[[ 5 25]
 [ 3  9]]


In [ ]:
x=np.array([[5,25],[3,9]])
x1=x.view()
x1[0]=111
print(x1)
print(x)

[[111 111]
 [  3   9]]
[[111 111]
 [  3   9]]


In [ ]:
y=np.arange(0,9)
print(y)
ycopy=y.copy()
ycopy[0]=100
print(ycopy)
print(y)

[0 1 2 3 4 5 6 7 8]
[100   1   2   3   4   5   6   7   8]
[0 1 2 3 4 5 6 7 8]


In [ ]:
y=np.arange(0,9)
print(y)
yview=y.view()
yview[0]=100
print(yview)
print(y)

[0 1 2 3 4 5 6 7 8]
[100   1   2   3   4   5   6   7   8]
[100   1   2   3   4   5   6   7   8]


In [ ]:
y=np.arange(0,9)
for i in np.nditer(y):
  print(i)


0
1
2
3
4
5
6
7
8


In [ ]:
y=np.arange(0,9)
for id,i in np.ndenumerate(y):
  print(id,i)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8


In [ ]:
for i in y:
  print(i)

0
1
2
3
4
5
6
7
8


In [ ]:
n1=np.array([41,42,43,44])
x=[True,False,True,False]
new1=n1[x]
print(new1)

[41 43]


In [ ]:
n1=np.array([41,42,43,44])
new2=np.where(n1>42)
print(new2)
print(n1[new2])

(array([2, 3]),)
[43 44]


In [ ]:
ar=np.arange(1,13)
print(ar)
ar_change=np.where(ar<5,ar*2,ar)
print(ar_change)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8  5  6  7  8  9 10 11 12]
