<a href="https://colab.research.google.com/github/rajshreeathawale/python_Ass/blob/main/python_ass_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lab Assignment 6 – Python**

Q1.Create a 4X2 integer array and Prints its attributes

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.T)
print(a.dtype)

2
(4, 2)
8
[[1 3 5 7]
 [2 4 6 8]]
int64


Q2.Create a 5X2 integer array from a range between 100 to 200 such
that the difference between each element is 10

In [ ]:
a= np.arange(100,200,10).reshape(5,2)
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Q3.Create a numPy array. Return array of items by taking the third
column from all rows

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:, 2])

[3 6 9]


Q4.Create a numpy array with 3 elements. Do all the arithmetic
operations with scalar element.

In [ ]:
a=np.array([10,20,30])
add=np.add(a,a)
print(add)
sub=np.subtract(a,a)
print(sub)
mul=np.multiply(a,a)
print(mul)
div=np.divide(a,a)
print(div)

[20 40 60]
[0 0 0]
[100 400 900]
[1. 1. 1.]


Q5.Create two 2-D numpy array. Do array concatenation, stack, vstack
and hstack on that.

In [ ]:
a1=np.array([[10,20],[30,40]])
a2=np.array([[50,60],[70,80]])
conc=np.concatenate((a1,a2))
print("concatination :",conc)

stack=np.stack((a1,a2))
print("stack :",stack)

vstack=np.vstack((a1,a2))
print("vstack :",vstack)

hstack=np.hstack((a1,a2))
print("hstack :",hstack)

concatination : [[10 20]
 [30 40]
 [50 60]
 [70 80]]
stack : [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
vstack : [[10 20]
 [30 40]
 [50 60]
 [70 80]]
hstack : [[10 20 50 60]
 [30 40 70 80]]


Q6.Create an Nd numpy array. Using array filter retrieve all the even
elements in that array.

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("a : ",a)
b=a%2==0
c=a[b]
print("c :",c)

a :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
c : [2 4 6 8]


Q7.Write a python program to read a dataset from titanic file and do
the following:

• Read values to dataframe and print the first 6 rows.

• Print the concise summary of the dataframe.

• calculate the mean of each numeric column in dataframe.

• find the count of null values in dataframe.

• Take the average people survived.

• Take the average male and female survived.

• Group the entire dataframe based on Gender and Pclass.

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('titanic.csv')
print(df.head(6))


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN       

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


In [ ]:
print(df.mean())

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64


<ipython-input-42-f98cceecb4a0>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df.mean())


In [ ]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
print(df['Survived'].mean())

0.3838383838383838


In [ ]:
print(df[df['Sex']=='male']['Survived'].mean())

0.18890814558058924


In [ ]:
print(df[df['Sex']=='female']['Survived'].mean())

0.7420382165605095


In [ ]:
a=df.groupby(['Sex','Pclass'])
print(a)
for Sex,Pclass in a:
    print(Sex)
    print(Pclass)


('female', 1)
     PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
11            12         1       1   
31            32         1       1   
52            53         1       1   
..           ...       ...     ...   
856          857         1       1   
862          863         1       1   
871          872         1       1   
879          880         1       1   
887          888         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   
..                                                 ... 

Q8Write a python program to read a dataset from weather file and do
the following:

• Read values to dataframe and print the first 6 rows.

• Print the concise summary of the dataframe.

• calculate the mean of each numeric column in dataframe.

• find the count of null values in dataframe.

• Take the maximum temperature from the weather data.

• Retrieve the average windspeed from the weather data.

• Make a new dataframe which contains minmum values of all
columns based on event.

• Make a new dataframe which contains minmum temperature based
on event.

In [ ]:
df1=pd.read_csv('weather.csv')
print(df1)
print('\n')
print("First six rows :\n",df1.head(6))


    Unnamed: 0         day  temperature  windspeed   event
0            0  01-01-2022         32.0        6.0    Rain
1            1  01-04-2022          NaN        9.0   Sunny
2            2  01-05-2022         28.0        NaN    Snow
3            3  01-06-2022          NaN        7.0     NaN
4            4  01-07-2022         32.0        NaN    Rain
5            5  01-08-2022          NaN        NaN   Sunny
6            6  01-09-2022          NaN        NaN     NaN
7            7  01-10-2022         34.0        8.0  Cloudy
8            8  01-10-2022         34.0        8.0  Cloudy
9            9  01-11-2022         40.0       12.0   Sunny
10          10  01-11-2022         40.0       12.0   Sunny


First six rows :
    Unnamed: 0         day  temperature  windspeed  event
0           0  01-01-2022         32.0        6.0   Rain
1           1  01-04-2022          NaN        9.0  Sunny
2           2  01-05-2022         28.0        NaN   Snow
3           3  01-06-2022          NaN      

In [ ]:
print("Concise summery of the Dataframe :\n")
print(df1.info())

Consise summery of the Dataframe :

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   11 non-null     int64  
 1   day          11 non-null     object 
 2   temperature  7 non-null      float64
 3   windspeed    7 non-null      float64
 4   event        9 non-null      object 
dtypes: float64(2), int64(1), object(2)
memory usage: 568.0+ bytes
None


In [ ]:
print("Mean of each numeric column :\n",df1.mean())

Mean of each numeric column :
 Unnamed: 0      5.000000
temperature    34.285714
windspeed       8.857143
dtype: float64


<ipython-input-69-720a9f7da456>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("Mean of each numeric column :\n",df1.mean())


In [ ]:
print("Count of all null values in dataframe :\n",df1.isnull().sum())

Count of all null values in dataframe :
 Unnamed: 0     0
day            0
temperature    4
windspeed      4
event          2
dtype: int64


In [ ]:
print("Maximum Temperature :\n",df1['temperature'].max())

Maximum Temperature :
 40.0


In [ ]:
print("Average windspeed :\n",df1['windspeed'].mean())

Average windspeed :
 8.857142857142858


In [ ]:
df2=df1.groupby('event').min()
print("Minimum value of all column based on events :\n",df2)

Minimum value of all column based on events :
         Unnamed: 0         day  temperature  windspeed
event                                                 
Cloudy           7  01-10-2022         34.0        8.0
Rain             0  01-01-2022         32.0        6.0
Snow             2  01-05-2022         28.0        NaN
Sunny            1  01-04-2022         40.0        9.0


In [ ]:
df3=df1.groupby('event')['temperature'].min()
print("Minimum temperature based on event :\n",df3)

Minimum temperature based on event :
 event
Cloudy    34.0
Rain      32.0
Snow      28.0
Sunny     40.0
Name: temperature, dtype: float64


Q9.Write a python program to read a dataset from diamonds file and
do the following:

• Read values to dataframe and print the first 6 rows.

• Print the concise summary of the dataframe.

• calculate the mean of each numeric column in dataframe.

• find the count of null values in dataframe.

• Calculate min, max price for each cut of diamonds.

• Take the count of all duplicate rows in the dataframe.

In [ ]:
d=pd.read_csv('diamonds.csv')
print(d)


       Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  

In [ ]:
print(d.head(6))

   Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0           1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1           2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2           3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3           4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4           5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
5           6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94   

      y     z  
0  3.98  2.43  
1  3.84  2.31  
2  4.07  2.31  
3  4.23  2.63  
4  4.35  2.75  
5  3.96  2.48  


In [ ]:
print(d.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object 
 3   color       53940 non-null  object 
 4   clarity     53940 non-null  object 
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB
None


In [ ]:
print("Mean of each numeric column:\n",d.mean())

Mean of each numeric column:
 Unnamed: 0    26970.500000
carat             0.797940
depth            61.749405
table            57.457184
price          3932.799722
x                 5.731157
y                 5.734526
z                 3.538734
dtype: float64


<ipython-input-86-32341de3cf5c>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("Mean of each numeric column:\n",d.mean())


In [ ]:
print("Cont of null values in each column :\n",d.isnull().sum())

Cont of null values in each column :
 Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64


In [ ]:
print("Min,Max price for each cut of diamond :\n",d.groupby('cut')['price'].agg(['min','max']))

Min,Max price for each cut of diamond :
            min    max
cut                  
Fair       337  18574
Good       327  18788
Ideal      326  18806
Premium    326  18823
Very Good  336  18818


In [ ]:
print(d.duplicated().sum())

0
